# Generated by Django 2.1.7 on 2020-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='participants',
            field=models.ManyToManyField(blank=True, to='contest.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
