# Generated by Django 2.1.7 on 2020-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
