# Generated by Django 2.1.7 on 2020-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20201025_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='participant',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.TextField(null=True),
        ),
    ]
