# Generated by Django 2.1.7 on 2020-12-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20201203_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='image_link',
            field=models.CharField(blank=True, default='/static/newtheme/img/test.jpeg', max_length=1000),
        ),
    ]
