# Generated by Django 2.1.7 on 2021-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20210303_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='penalty_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
