# Generated by Django 2.1.7 on 2020-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200406_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_discussion',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_reply',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='discussion_author',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='discussion_tags',
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='problems_solved',
            field=models.ManyToManyField(blank=True, to='myapp.Problem'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Test_Case',
        ),
    ]
