# Generated by Django 2.1.7 on 2020-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.CharField(default='no_label', max_length=200),
        ),
    ]
