# Generated by Django 2.2.14 on 2020-08-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_interviewexperiences'),
        ('myapp', '0008_blogs'),
    ]

    operations = [
    ]
