# Generated by Django 2.1.7 on 2020-08-05 19:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20200804_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('instructors', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('enrolledusers', models.ManyToManyField(blank=True, to='myapp.Custom_User')),
                ('notesincourse', models.ManyToManyField(blank=True, to='myapp.Note')),
            ],
        ),
    ]
