# Generated by Django 2.1.7 on 2020-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('discount', models.IntegerField(default=0)),
                ('assignedto', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
