# Generated by Django 2.1.7 on 2020-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewexperiences',
            name='companyname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
