# Generated by Django 2.1.7 on 2020-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_custom_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='end_date',
            field=models.CharField(default='No Course Purchased', max_length=200),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='start_date',
            field=models.CharField(default='No Course Purchased', max_length=200),
        ),
    ]
