# Generated by Django 2.1.7 on 2020-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200930_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='points_earned',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='universitycgpa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='universityendyear',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='universitystartyear',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
