# Generated by Django 2.1.7 on 2020-10-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200930_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='questionsallotted',
            field=models.TextField(default='No Mentor Allotted ! Mentors allot questions every week for practice according to learning pace of each individual student. Purchase a course to get a mentor assigned to you.'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='scheduledclass',
            field=models.TextField(default='No One to One Class Scheduled ! Mentors take One-to-One Class of each individual student. Purchase a course to get One to One Classes with mentors.'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
