# Generated by Django 2.1.7 on 2020-10-04 11:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20201004_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='questionsallotted',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='No Mentor Allotted ! Mentors allot questions every week for practice according to learning pace of each individual student. Purchase a course to get a mentor assigned to you.', null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='scheduledclass',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='No One to One Class Scheduled ! Mentors take One-to-One Class of each individual student. Purchase a course to get One to One Classes with mentors.', null=True),
        ),
    ]
