# Generated by Django 2.1.7 on 2020-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20201004_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='analyse_link',
            field=models.TextField(blank=True),
        ),
    ]
