# Generated by Django 2.1.7 on 2020-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_freetrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
