# Generated by Django 2.2.14 on 2020-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_custom_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='referral_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
