# Generated by Django 2.1.7 on 2020-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='questionsallotted',
            field=models.TextField(blank=True, default='No Mentor Allotted ! Mentors allot questions every week for practice according to learning pace of each individual student. Purchase a course to get a mentor assigned to you.', null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='scheduledclass',
            field=models.CharField(blank=True, default='No One to One Class Scheduled ! Mentors take One-to-One Class of each individual student. Purchase a course to get One to One Classes with mentors.', max_length=200, null=True),
        ),
    ]
