# Generated by Django 2.1.7 on 2020-11-24 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20201124_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='questionsallotted',
            field=ckeditor.fields.RichTextField(blank=True, default='No Mentor Allotted ! Mentors allot questions every week for practice according to learning pace of each individual student. Purchase a course to get a mentor assigned to you.', null=True),
        ),
    ]
