# Generated by Django 2.1.7 on 2020-11-24 11:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20201124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='scheduledclass',
            field=ckeditor.fields.RichTextField(blank=True, default='No One to One Class Scheduled ! Mentors take One-to-One Class of each individual student. Purchase a course to get One to One Classes with mentors.', null=True),
        ),
    ]
