# Generated by Django 2.1.7 on 2020-12-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='current_topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mentor_user',
            name='course_alloted',
            field=models.CharField(default='no course alloted', max_length=200),
        ),
    ]
