# Generated by Django 2.1.7 on 2020-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20201230_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor_Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(blank=True, max_length=14)),
                ('availability', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('achievements', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
        ),
    ]
