# Generated by Django 2.1.7 on 2020-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_mentor_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_lead',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
