# Generated by Django 2.1.7 on 2020-12-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20201231_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_lead',
            name='resume',
            field=models.FileField(blank=True, default='resume.txt', upload_to='resume/'),
        ),
    ]
