# Generated by Django 2.1.7 on 2021-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20201231_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_lead',
            name='resume',
            field=models.FileField(blank=True, default=None, upload_to='resume/'),
        ),
    ]
