# Generated by Django 2.1.7 on 2021-01-15 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20210115_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
