# Generated by Django 2.1.7 on 2021-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20210115_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='from_time',
            field=models.TimeField(),
        ),
    ]
