# Generated by Django 2.1.7 on 2021-02-25 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20210115_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='group_date1',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='courses',
            name='group_date2',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='courses',
            name='group_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='group_seat1',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='courses',
            name='group_seat2',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
