# Generated by Django 2.1.7 on 2021-05-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_groups_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='current_topic',
            field=models.TextField(default='Array:00000; javasprings:0000; Binary Search Tree:00000; Sorting:00000000; Divide And Conquer:00000; djangoviews:00; pythonflask:; Graph:000; Searching:0000; Mathematical:0000; Pattern Matching:000; flaskrouting:00; ibmbluemix:; Divide And Conquers:00000; flaskmethods:00; pythondjango:; djangomodels:000; djangoforms:00; Dynamic Programming:0000; Stack:000; Binary Tree:0000; firebase:; back Tracking:000; Binary Search Tree:00000; pythonconditions:00; heroku:; s:; Queue:000; Graph Algorithms:000; pythonfunctions:00; Dynamic Programmings:0000; djangodeployment:00; pythondatatypes:0000; pythonoperators:00000000; flasktemplates:00; flaskbasics:00; Hashing:000; Greedy:00000; flaskdeployment:00; pythonloops:00000; Strings:00; csharpdotnet:; awss:; djangobasics:0000; Linked List:0000;STL:0000;'),
        ),
    ]
