# Generated by Django 2.1.7 on 2021-05-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20210519_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups_learn',
            name='mentor_alloted',
        ),
        migrations.AddField(
            model_name='mentor_user',
            name='groupalloted',
            field=models.ManyToManyField(blank=True, to='myapp.Groups_learn'),
        ),
    ]
