# Generated by Django 2.1.7 on 2021-05-30 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0047_auto_20210529_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='fullname', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('college_name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=13)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('studentCount', models.CharField(default='0', max_length=500)),
                ('allotedstudents', models.ManyToManyField(blank=True, to='myapp.Custom_User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
