# Generated by Django 2.1.7 on 2021-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_ambassadoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courselink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='faqanswer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='faqquestion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='topiccovered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='videolink',
            field=models.URLField(blank=True),
        ),
    ]
