# Generated by Django 2.1.7 on 2021-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20210612_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=500)),
                ('Resume', models.FileField(blank=True, default=None, upload_to='resume/')),
                ('Year', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], default='1', max_length=20)),
            ],
        ),
    ]
