# Generated by Django 2.1.7 on 2021-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_algoedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoedge',
            name='phone',
            field=models.CharField(default=7906334045, max_length=500),
            preserve_default=False,
        ),
    ]
