# Generated by Django 4.1 on 2022-09-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20210720_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='myapp.track'),
        ),
    ]
